# -*- coding: utf-8 -*-
"""asg[3].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeqfrX0pwW_PvPjC8dFKESku0Kk9WUkj
"""

# payoff matrix

from itertools import combinations_with_replacement, permutations
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Generate all valid allocations of 7 legions across 3 passes
def generate_allocations(total, parts):
    allocations = []
    for x in range(total + 1):
        for y in range(total + 1 - x):
            z = total - x - y
            allocations.append((x, y, z))
    return allocations

# Compare two allocations and determine the outcome
def compare_allocations(a, b):
    a_wins = sum(1 for ai, bi in zip(a, b) if ai > bi)
    b_wins = sum(1 for ai, bi in zip(a, b) if ai < bi)
    if a_wins > b_wins:
        return 1
    elif a_wins < b_wins:
        return -1
    else:
        return 0

# Generate all allocations
allocations = generate_allocations(7, 3)
n = len(allocations)

# Initialize payoff matrix
payoff_matrix = np.zeros((n, n), dtype=int)

# Fill in the matrix
for i, a in enumerate(allocations):
    for j, b in enumerate(allocations):
        payoff_matrix[i, j] = compare_allocations(a, b)

# Print matrix (optional)
print("Payoff matrix shape:", payoff_matrix.shape)
print(payoff_matrix)

# Create DataFrame
pom = pd.DataFrame(payoff_matrix)

# Plot as table
fig, ax = plt.subplots()
ax.axis('off')
table = ax.table(cellText=pom.values, colLabels=pom.columns, rowLabels=pom.index, loc='center')
table.auto_set_font_size(False)
table.set_fontsize(12)

# Save as image
plt.savefig("matrix_table.png", bbox_inches='tight', dpi=300)
plt.savefig("matrix_table.pdf", bbox_inches='tight')
plt.show()

#visualizing heatmap of payoff matrix

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 8))
sns.heatmap(payoff_matrix, cmap="coolwarm", center=0, cbar_kws={"label": "Payoff"})
plt.title("Payoff Matrix Heatmap (Antigonus vs. Brasidas)")
plt.xlabel("Brasidas' Allocations (Columns)")
plt.ylabel("Antigonus' Allocations (Rows)")
plt.tight_layout()
plt.show()

import numpy as np
from scipy.optimize import linprog


P = np.array(payoff_matrix)

m, n = P.shape

# We are solving for variables x_1, ..., x_m and v (so m+1 variables)
# Let the variable vector be [x_1, ..., x_m, v]

# Objective: minimize -v → c = [0, 0, ..., 0, -1]
c = np.zeros(m + 1)
c[-1] = -1

# Inequality constraints
A_ub = np.hstack([-P.T, np.ones((n, 1))])  # shape (n, m+1)
b_ub = np.zeros(n)

# Equality constraint
A_eq = np.zeros((1, m + 1))
A_eq[0, :m] = 1
b_eq = [1]

# Bounds
bounds = [(0, None)] * m + [(None, None)]

res = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')

#results
if res.success:
    x_opt = res.x[:m]
    v_opt = res.x[-1]
    print("Optimal strategy for Antigonus (x):", x_opt)
    print("Optimal expected payoff (v):", v_opt)
else:
    print("Linear programming failed:", res.message)

import numpy as np
from itertools import product
from scipy.optimize import linprog
import matplotlib.pyplot as plt

def generate_allocations(total):
    allocations = []
    for x in range(total + 1):
        for y in range(total + 1 - x):
            z = total - x - y
            allocations.append((x, y, z))
    return allocations

def compare_allocations(a, b):
    a_wins = sum(ai > bi for ai, bi in zip(a, b))
    b_wins = sum(ai < bi for ai, bi in zip(a, b))
    return 1 if a_wins > b_wins else -1 if a_wins < b_wins else 0

# For storing results
legion_counts = list(range(5, 10))
support_sizes = []
expected_payoffs = []
pure_strategies = []

for total_legions in legion_counts:
    print(f"\n--- Total Legions: {total_legions} ---")
    allocations = generate_allocations(total_legions)
    m = len(allocations)
    P = np.zeros((m, m), dtype=int)

    for i, a in enumerate(allocations):
        for j, b in enumerate(allocations):
            P[i, j] = compare_allocations(a, b)

    # LP setup
    c = np.zeros(m + 1)
    c[-1] = -1  # maximize v -> minimize -v

    A_ub = np.hstack([-P.T, np.ones((m, 1))])
    b_ub = np.zeros(m)

    A_eq = np.zeros((1, m + 1))
    A_eq[0, :m] = 1
    b_eq = [1]

    bounds = [(0, None)] * m + [(None, None)]

    res = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')

    if res.success:
        x_opt = res.x[:m]
        v_opt = res.x[-1]
        support = np.where(x_opt > 1e-6)[0]

        support_sizes.append(len(support))
        expected_payoffs.append(v_opt)
        if len(support) == 1:
            pure_strategies.append(allocations[support[0]])
        else:
            pure_strategies.append(None)

        print(f"Expected payoff: {v_opt:.4f}")
        print(f"Number of allocations in support: {len(support)}")
        if len(support) == 1:
            print(f"Pure strategy found: {allocations[support[0]]}")
        else:
            print("Optimal strategy is mixed (randomized).")
    else:
        print("LP solution failed.")
        support_sizes.append(None)
        expected_payoffs.append(None)
        pure_strategies.append(None)

# Plotting
plt.figure(figsize=(12, 5))

# Support size plot
plt.subplot(1, 2, 1)
plt.plot(legion_counts, support_sizes, marker='o')
plt.title("Support Size of Optimal Strategy")
plt.xlabel("Total Legions")
plt.ylabel("Number of Allocations in Support")

# Expected payoff plot
plt.subplot(1, 2, 2)
plt.plot(legion_counts, expected_payoffs, marker='s', color='green')
plt.title("Optimal Expected Payoff (Antigonus)")
plt.xlabel("Total Legions")
plt.ylabel("Expected Payoff")

plt.tight_layout()
plt.show()

# Print summary of pure strategy cases
for total, strat in zip(legion_counts, pure_strategies):
    if strat is not None:
        print(f"[Summary] Pure strategy found for {total} legions: {strat}")

import numpy as np
from scipy.optimize import linprog

# Assume you already have `payoff_matrix` defined from earlier
P = np.array(payoff_matrix)
m, n = P.shape

# We are solving for y_1, ..., y_n and w (so n+1 variables)
# Objective: minimize w → c = [0,...,0, 1]
c = np.zeros(n + 1)
c[-1] = 1  # w

# Inequality
A_ub = np.hstack([P, -np.ones((m, 1))])
b_ub = np.zeros(m)

# Equality
A_eq = np.zeros((1, n + 1))
A_eq[0, :n] = 1
b_eq = [1]

# Bounds
bounds = [(0, None)] * n + [(None, None)]

res = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')

if res.success:
    y_opt = res.x[:n]
    w_opt = res.x[-1]
    print("Optimal strategy for Brasidas (y):", y_opt)
    print("Expected payoff for Brasidas (−v):", -w_opt)
else:
    print("Linear programming failed:", res.message)