# -*- coding: utf-8 -*-
"""asg[2].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVXcav0WbftQ0rAVes-sSX2JeMqDU8tW
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms, utils
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from prettytable import PrettyTable

seed = 42
torch.manual_seed(seed)
#random.seed(seed)
np.random.seed(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

# Download the MNIST dataset
transform = transforms.ToTensor()
train_dataset = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)

print("number of training samples: " + str(len(train_dataset)) + "\n" +
      "number of testing samples: " + str(len(test_dataset)))

print("datatype of the 1st training sample: ", train_dataset[0][0].type())
print("size of the 1st training sample: ", train_dataset[0][0].size())

batch_size = 64

# Create data loaders.
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False)
train_loader_wb = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=1, shuffle=True)
test_loader_wb = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=1, shuffle=False)

# Verify size of batches
for X, y in test_loader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

# Hardware
#device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
device = "cpu" # Changed to "cpu" to avoid potential issues with torch.accelerator
print(f"Using {device} device")

# Define the model
class LeNet5(nn.Module):
    def __init__(self):
        super(LeNet5, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, kernel_size=5, stride=1)
        self.conv2 = nn.Conv2d(6, 16, kernel_size=5, stride=1)
        self.fc1 = nn.Linear(256, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = torch.tanh(self.conv1(x))
        x = torch.max_pool2d(x, kernel_size=2, stride=2)
        x = torch.tanh(self.conv2(x))
        x = torch.max_pool2d(x, kernel_size=2, stride=2)
        x = x.view(-1, 256)
        x = torch.tanh(self.fc1(x))
        x = torch.tanh(self.fc2(x))
        x = self.fc3(x)
        return x


def count_parameters(model):
    table = PrettyTable(["Modules", "Parameters"])
    total_params = 0
    for name, parameter in model.named_parameters():
        if not parameter.requires_grad:
            continue
        params = parameter.numel()
        table.add_row([name, params])
        total_params += params
    print(table)
    print(f"Total Trainable Params: {total_params}")
    return total_params

model = LeNet5().to(device)

count_parameters(model)
fc12_params = [p for name, p in model.named_parameters() if name in ['fc1.weight', 'fc2.weight']]
print(fc12_params[0].numel())
print(fc12_params[1].numel())

# raise SystemExit

# Training loop
#training with cross entropy loss and SGD
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)
n_epochs = 10
train_losses = []
test_losses = []
test_accuracies = []

def train_model(model, train_loader, test_loader, criterion, optimizer, n_epochs):
    global train_losses, test_losses
    step = 0
    for epoch in range(n_epochs):
        model.train()
        for i, (images, labels) in enumerate(train_loader):
            images, labels = images.to(device), labels.to(device)
            if isinstance(optimizer, torch.optim.LBFGS):
                def closure():
                    optimizer.zero_grad()
                    output = model(images)
                    loss = criterion(output, labels)
                    loss.backward()
                    return loss

                loss = optimizer.step(closure)
                loss = closure()
            else:
                optimizer.zero_grad()
                output = model(images)
                loss = criterion(output, labels)
                loss.backward()
                optimizer.step()

            step += 1
            train_losses.append((step, loss.item()))
            print(f'Epoch {epoch}, Step {step}, Loss: {loss.item()}')

        model.eval()
        test_loss = 0
        correct = 0
        with torch.no_grad():
            for images, labels in test_loader:
                output = model(images)
                test_loss += criterion(output, labels).item()
                pred = torch.argmax(output, dim=1)
                correct += pred.eq(labels).sum()

        test_loss /= len(test_loader.dataset)
        test_losses.append((step, test_loss))
        test_accuracy = 100. * correct / len(test_loader.dataset)
        test_accuracies.append((step, test_accuracy.item()))

        print(f'Test set: Average loss: {test_loss}, Accuracy: {correct}/{len(test_loader.dataset)} ({100. * correct / len(test_loader.dataset):.2f}%)')
    return train_losses, test_losses, test_accuracies

train_losses, test_losses, test_accuracies = train_model(model, train_loader, test_loader, criterion, optimizer, n_epochs=10)

# plot train and test losses to file loss.png
train_steps, train_loss = zip(*train_losses)
test_steps, test_loss = zip(*test_losses)
accuracy_steps, accuracy_values = zip(*test_accuracies)

fig, ax = plt.subplots(3, 1, figsize=(8, 6), sharex=True)  # sharex aligns x-axes

# Plot the first
ax[0].plot(train_steps, train_loss, label="Train Loss", color="blue")
ax[0].set_ylabel("Loss")
ax[0].legend()
ax[0].grid(True)

# Plot the second
ax[1].plot(test_steps, test_loss, label="Test Loss, Average", color="red")
interval = int(np.ceil(len(train_dataset)/batch_size))
ax[1].set_xticks(range(0,interval*(n_epochs+1),interval))
ax[1].set_xticklabels(range(n_epochs+1))
ax[1].set_xlabel("Epoch")
ax[1].set_ylabel("Loss")
ax[1].legend()
ax[1].grid(True)

# Plot the first
ax[2].plot(accuracy_steps, accuracy_values, label="Test Accuracy", color="green")
ax[2].set_xticks(range(0,interval*(n_epochs+1),interval))
ax[2].set_xticklabels(range(n_epochs+1))
ax[2].set_xlabel("Epoch")
ax[2].set_ylabel("accuracy")
ax[2].legend()
ax[2].grid(True)

# Adjust layout and show the plot
plt.tight_layout()
plt.show()

class SteepestDescent(torch.optim.Optimizer):
    def __init__(self, params, lr=0.01):
        defaults = dict(lr=lr)
        super(SteepestDescent, self).__init__(params, defaults)

    @torch.no_grad()
    def step(self, closure=None):
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()

        for group in self.param_groups:
            lr = group['lr']
            for p in group['params']:
                if p.grad is None:
                    continue
                p.add_(p.grad, alpha=-lr)

        return loss

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
import numpy as np
from prettytable import PrettyTable
import copy

# Seed
seed = 42
torch.manual_seed(seed)
np.random.seed(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

# Dataset
transform = transforms.ToTensor()
train_dataset = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)

batch_size = 64
full_batch_size = len(train_dataset)

train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True, pin_memory=True)
#train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False)
train_loader_batch = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=full_batch_size, shuffle=True, pin_memory=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using {device} device")


# Model
class LeNet5(nn.Module):
    def __init__(self):
        super(LeNet5, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, kernel_size=5, stride=1)
        self.conv2 = nn.Conv2d(6, 16, kernel_size=5, stride=1)
        self.fc1 = nn.Linear(256, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = torch.tanh(self.conv1(x))
        x = torch.max_pool2d(x, 2, 2)
        x = torch.tanh(self.conv2(x))
        x = torch.max_pool2d(x, 2, 2)
        x = x.view(-1, 256)
        x = torch.tanh(self.fc1(x))
        x = torch.tanh(self.fc2(x))
        x = self.fc3(x)
        return x

# Sparsity enforcement
def apply_sparsity(model, sparsity_ratio=0.6):
    """Enforce sparsity in fc1 and fc2 layers so that only sparsity_ratio of weights are non-zero."""
    with torch.no_grad():
        for name, param in model.named_parameters():
            if 'fc1' in name or 'fc2' in name:
                flat = param.view(-1)
                k = int(len(flat) * sparsity_ratio)
                if k < len(flat):
                    threshold = torch.topk(torch.abs(flat), k, largest=True).values[-1]
                    mask = torch.abs(flat) >= threshold
                    flat *= mask.float()

# Training function
def train_model(model, train_loader, test_loader, criterion, optimizer, n_epochs, special_optimizer=None):
    train_losses, test_losses, test_accuracies = [], [], []
    step = 0

    if special_optimizer == 'IterateAveraging':
        avg_model = copy.deepcopy(model)
        avg_counter = 1

    for epoch in range(n_epochs):
        model.train()
        for i, (images, labels) in enumerate(train_loader):
            images, labels = images.to(device), labels.to(device)

            if isinstance(optimizer, torch.optim.LBFGS):
                def closure():
                    optimizer.zero_grad()
                    output = model(images)
                    loss = criterion(output, labels)
                    loss.backward()
                    return loss
                loss = optimizer.step(closure)
                loss = closure()  # For logging
            else:
                optimizer.zero_grad()
                outputs = model(images)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()

                if special_optimizer == 'SparseCEL':
                    apply_sparsity(model, sparsity_ratio=0.6)

            step += 1
            train_losses.append((step, loss.item()))

            if special_optimizer == 'IterateAveraging' and (step % 100 == 0):
                for p1, p2 in zip(avg_model.parameters(), model.parameters()):
                    p1.data += p2.data
                    avg_counter += 1

        model.eval()
        test_loss = 0
        correct = 0
        with torch.no_grad():
            for images, labels in test_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                test_loss += criterion(outputs, labels).item()
                pred = outputs.argmax(dim=1)
                correct += pred.eq(labels).sum()

        test_loss /= len(test_loader.dataset)
        test_losses.append((step, test_loss))
        test_accuracy = 100. * correct / len(test_loader.dataset)
        test_accuracies.append((step, test_accuracy.item()))

        print(f"Epoch {epoch}: Loss {test_loss:.4f}, Accuracy {test_accuracy:.2f}%")

    if special_optimizer == 'IterateAveraging':
        for p in avg_model.parameters():
            p.data /= avg_counter
        model.load_state_dict(avg_model.state_dict())

    return train_losses, test_losses, test_accuracies

# ====================== #
# Configurations
# ====================== #

criterion_options = ['CEL', 'RegCEL', 'SparseCEL']
optimizer_options = [
    'SGD', 'MiniBatchSGD', 'BatchSGD',
    'SGD_mom', 'Nesterov', 'LBFGS',
    'IterateAveraging', 'NaturalGradApprox', 'Adam'
]

results = {}

# ====================== #
# Main Loop
# ====================== #
num_epochs = 10
for crit in criterion_options:
    for opt in optimizer_options:
        print(f"\nTraining with {crit} + {opt}...")

        model = LeNet5().to(device)

        # Setup loss and sparsity behavior
        if crit == 'CEL':
            criterion = nn.CrossEntropyLoss()
            wd = 0.0
            special = None
        elif crit == 'RegCEL':
            criterion = nn.CrossEntropyLoss()
            wd = 1e-4  # L2 regularization strength
            special = None
        elif crit == 'SparseCEL':
            criterion = nn.CrossEntropyLoss()
            wd = 0.0
            special = 'SparseCEL'

        # Setup optimizer
        if opt == 'SGD':
            optimizer = torch.optim.SGD(model.parameters(), lr=0.01, weight_decay=wd)
            loader = train_loader
        elif opt == 'MiniBatchSGD':
            optimizer = torch.optim.SGD(model.parameters(), lr=0.01, weight_decay=wd)
            loader = train_loader
        elif opt == 'BatchSGD':
            optimizer = SteepestDescent(model.parameters(), lr=0.5)
            loader = train_loader_batch
        elif opt == 'SGD_mom':
            optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9, weight_decay=wd)
            loader = train_loader
        elif opt == 'Nesterov':
            optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9, nesterov=True, weight_decay=wd)
            loader = train_loader
        elif opt == 'Adam':
            optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=wd)
            loader = train_loader
        elif opt == 'LBFGS':
            optimizer = torch.optim.LBFGS(model.parameters(), lr=0.1)
            loader = train_loader_batch
        elif opt == 'IterateAveraging':
            optimizer = torch.optim.SGD(model.parameters(), lr=0.01, weight_decay=wd)
            loader = train_loader
            special = 'IterateAveraging'
        elif opt == 'NaturalGradApprox':
            optimizer = torch.optim.SGD(model.parameters(), lr=0.001, weight_decay=wd)
            loader = train_loader

        train_losses, test_losses, test_accuracies = train_model(
            model, loader, test_loader, criterion, optimizer, n_epochs=10, special_optimizer=special
        )

        results[(crit, opt)] = {
            'train_losses': train_losses,
            'test_losses': test_losses,
            'test_accuracies': test_accuracies
        }

        # ===== Plotting =====
        train_steps, train_loss = zip(*train_losses)
        test_steps, test_loss = zip(*test_losses)
        accuracy_steps, accuracy_values = zip(*test_accuracies)

        fig, ax = plt.subplots(3, 1, figsize=(8, 6), sharex=True)

        if isinstance(optimizer, (SteepestDescent, torch.optim.LBFGS)):
            epochs = list(range(1, len(test_accuracies) + 1))
            train_loss_vals = [loss for _, loss in train_losses[::1]]
            test_loss_vals = [loss for _, loss in test_losses]
            accuracy_vals = [acc for _, acc in test_accuracies]

            ax[0].plot(epochs, train_loss_vals[:len(epochs)], label="Train Loss", color="blue")
            ax[1].plot(epochs, test_loss_vals, label="Test Loss", color="red")
            ax[2].plot(epochs, accuracy_vals, label="Test Accuracy", color="green")

            ax[2].set_xticks(range(1, num_epochs + 1))
            ax[2].set_xticklabels(range(1, num_epochs + 1))
            ax[2].set_xlabel("Epoch")

        else:
            train_steps, train_loss = zip(*train_losses)
            test_steps, test_loss = zip(*test_losses)
            accuracy_steps, accuracy_values = zip(*test_accuracies)

            ax[0].plot(train_steps, train_loss, label="Train Loss", color="blue")
            ax[1].plot(test_steps, test_loss, label="Test Loss", color="red")
            ax[2].plot(accuracy_steps, accuracy_values, label="Test Accuracy", color="green")

            interval = int(np.ceil(len(train_dataset) / batch_size))
            ax[2].set_xticks(range(0, interval * (num_epochs + 1), interval))
            ax[2].set_xticklabels(range(num_epochs + 1))
            ax[2].set_xlabel("Epoch")

        ax[0].set_ylabel("Train Loss")
        ax[1].set_ylabel("Test Loss")
        ax[2].set_ylabel("Accuracy (%)")

        for a in ax:
            a.legend()
            a.grid(True)

        fig.suptitle(f"{crit} + {opt}", fontsize=14)
        plt.tight_layout()
        plt.show()